import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import Providers from "./providers";
import ThemeRegistry from "@/theme/ThemeRegistry";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const codecPro = localFont({
  src: [
    {
      path: "../../public/fonts/CodecPro-Regular.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/CodecPro-Italic.woff2",
      weight: "500",
      style: "italic",
    },
  ],
  variable: "--font-codec-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${codecPro.variable}`}
    >
      <body>
        <ThemeRegistry>
          <Providers>{children}</Providers>
        </ThemeRegistry>
      </body>
    </html>
  );
}
